android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
# Run Kotlin compiler IN PROCESS (no separate daemon = no crash)
kotlin.compiler.execution.strategy=in-process
# Gradle settings
org.gradle.jvmargs=-Xmx4g -XX:+UseG1GC -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -XX:SoftRefLRUPolicyMSPerMB=0
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.workers.max=3
org.gradle.configureondemand=false
