/*
 * IL2CPP Runtime Dumper - Standalone C binary
 * Runs with root to dump IL2CPP metadata from game process memory
 * Generated by OprekTool v0.16.0
 *
 * Usage: il2cpp_dumper <pid> <lib_name> <output_dir>
 * Example: il2cpp_dumper 12345 libil2cpp.so /sdcard/Download/OprekTool/dump
 *
 * This program:
 * 1. Reads /proc/<pid>/maps to find lib base address
 * 2. Scans memory for IL2CPP metadata magic (0xFAB11BAF)
 * 3. Parses TypeDef/MethodDef/FieldDef from metadata
 * 4. Generates dump.cs file
 * 5. Extracts all printable strings from library
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <ctype.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <sys/mman.h>
#include <sys/stat.h>

// IL2CPP metadata structures (simplified)
#pragma pack(push, 1)

typedef struct {
    uint32_t magic;           // 0xFAB11BAF
    uint32_t version;
    uint32_t stringLiteralOffset;
    uint32_t stringLiteralCount;
    uint32_t stringLiteralDataOffset;
    uint32_t stringLiteralDataCount;
    uint32_t stringOffset;
    uint32_t stringCount;
    uint32_t eventsOffset;
    uint32_t eventsCount;
    uint32_t propertiesOffset;
    uint32_t propertiesCount;
    uint32_t methodsOffset;
    uint32_t methodsCount;
    uint32_t parameterDefaultValuesOffset;
    uint32_t parameterDefaultValuesCount;
    uint32_t fieldDefaultValuesOffset;
    uint32_t fieldDefaultValuesCount;
    uint32_t fieldAndParameterDefaultValueDataOffset;
    uint32_t fieldAndParameterDefaultValueDataCount;
    uint32_t fieldMarshaledSizesOffset;
    uint32_t fieldMarshaledSizesCount;
    uint32_t parametersOffset;
    uint32_t parametersCount;
    uint32_t fieldsOffset;
    uint32_t fieldsCount;
    uint32_t genericParametersOffset;
    uint32_t genericParametersCount;
    uint32_t genericParameterConstraintsOffset;
    uint32_t genericParameterConstraintsCount;
    uint32_t genericContainersOffset;
    uint32_t genericContainersCount;
    uint32_t nestedTypesOffset;
    uint32_t nestedTypesCount;
    uint32_t interfacesOffset;
    uint32_t interfacesCount;
    uint32_t vtableMethodsOffset;
    uint32_t vtableMethodsCount;
    uint32_t interfaceOffsetsOffset;
    uint32_t interfaceOffsetsCount;
    uint32_t typeDefinitionsOffset;
    uint32_t typeDefinitionsCount;
    uint64_tRGCTXOffset;  // Removed for compatibility
    uint32_t rgctxEntriesOffset;
    uint32_t rgctxEntriesCount;
    uint32_t imagesOffset;
    uint32_t imagesCount;
    uint32_t assembliesOffset;
    uint32_t assembliesCount;
    uint32_t metadataUsageListsOffset;
    uint32_t metadataUsageListsCount;
    uint32_t metadataUsagePairsOffset;
    uint32_t metadataUsagePairsCount;
    uint32_t fieldRefsOffset;
    uint32_t fieldRefsCount;
    uint32_t referencedAssembliesOffset;
    uint32_t referencedAssembliesCount;
    uint32_t attributesInfoOffset;
    uint32_t attributesInfoCount;
    uint32_t attributeTypesInfoOffset;
    uint32_t attributeTypesInfoCount;
    uint32_t unresolvedVirtualCallParameterTypesOffset;
    uint32_t unresolvedVirtualCallParameterTypesCount;
    uint32_t unresolvedVirtualCallParameterRangesOffset;
    uint32_t unresolvedVirtualCallParameterRangesCount;
    uint32_t windowsRuntimeTypeNamesOffset;
    uint32_t windowsRuntimeTypeNamesSize;
    uint32_t exportedTypeDefinitionsOffset;
    uint32_t exportedTypeDefinitionsCount;
} Il2CppGlobalMetadataHeader;

// Simplified TypeDefinition (offsets depend on version)
typedef struct {
    uint32_t nameIndex;
    uint32_t namespaceIndex;
    uint32_t byvalTypeIndex;
    uint32_t declaringTypeIndex;
    uint32_t parentIndex;
    uint32_t elementTypeIndex;
    uint32_t rgctxStartIndex;
    uint32_t rgctxCount;
    uint32_t genericContainerIndex;
    uint32_t flags;
    uint32_t fieldStart;
    uint32_t methodStart;
    uint32_t eventStart;
    uint32_t propertyStart;
    uint32_t nestedTypesStart;
    uint32_t interfacesStart;
    uint32_t vtableStart;
    uint32_t interfaceOffsetsStart;
    uint16_t method_count;
    uint16_t property_count;
    uint16_t field_count;
    uint16_t event_count;
    uint16_t nested_type_count;
    uint16_t vtable_count;
    uint16_t interfaces_count;
    uint16_t interface_offsets_count;
    uint32_t bitfield;
    uint32_t token;
} Il2CppTypeDefinition;

// Simplified MethodDefinition
typedef struct {
    uint32_t nameIndex;
    uint32_t declaringType;
    uint32_t returnType;
    uint32_t parameterStart;
    uint32_t genericContainerIndex;
    uint32_t methodIndex;
    virtualIndex;
    uint32_t slot;
    uint32_t flags;
    uint32_t iflags;
    uint16_t slot;
    uint16_t parameterCount;
    uint32_t token;
} Il2CppMethodDefinition;

// Simplified FieldDefinition
typedef struct {
    uint32_t nameIndex;
    uint32_t token;
    uint32_t typeIndex;
    uint32_t parentIndex;
    uint32_t bitfield;
} Il2CppFieldDefinition;

#pragma pack(pop)

// Memory region info
typedef struct {
    unsigned long start;
    unsigned long end;
    unsigned long offset;
    char perms[5];
    char path[256];
} MemRegion;

// Globals
static int g_pid = -1;
static char g_lib_name[256] = {0};
static char g_output_dir[512] = {0};
static FILE *g_log = NULL;

#define LOG(fmt, ...) do { \
    fprintf(stderr, fmt "\n", ##__VA_ARGS__); \
    if (g_log) { fprintf(g_log, fmt "\n", ##__VA_ARGS__); fflush(g_log); } \
} while(0)

#define MAX_REGIONS 4096
#define MAX_DUMP_SIZE (256 * 1024 * 1024)  // 256MB max
#define METADATA_MAGIC 0xFAB11BAF

// Read all memory maps for the process
static int read_maps(MemRegion *regions, int max_regions) {
    char maps_path[64];
    snprintf(maps_path, sizeof(maps_path), "/proc/%d/maps", g_pid);
    
    FILE *f = fopen(maps_path, "r");
    if (!f) {
        LOG("[-] Cannot open %s: %s", maps_path, strerror(errno));
        return -1;
    }
    
    int count = 0;
    char line[1024];
    
    while (fgets(line, sizeof(line), f) && count < max_regions) {
        MemRegion *r = &regions[count];
        
        // Parse: addr-addr perms offset dev inode pathname
        if (sscanf(line, "%lx-%lx %4s %lx %*s %*s %255[^\n]",
                   &r->start, &r->end, r->perms, &r->offset, r->path) >= 4) {
            // Trim path
            char *p = r->path;
            while (*p == ' ') p++;
            memmove(r->path, p, strlen(p) + 1);
            count++;
        }
    }
    
    fclose(f);
    return count;
}

// Find the library base address and all its regions
static unsigned long find_lib_base(MemRegion *regions, int count, unsigned long *lib_end) {
    unsigned long base = 0;
    *lib_end = 0;
    
    for (int i = 0; i < count; i++) {
        if (strstr(regions[i].path, g_lib_name) && regions[i].perms[0] == 'r') {
            if (base == 0 || regions[i].start < base) {
                base = regions[i].start;
            }
            if (regions[i].end > *lib_end) {
                *lib_end = regions[i].end;
            }
        }
    }
    
    return base;
}

// Read memory from /proc/pid/mem
static int read_mem(unsigned long addr, void *buf, size_t len) {
    char mem_path[64];
    snprintf(mem_path, sizeof(mem_path), "/proc/%d/mem", g_pid);
    
    int fd = open(mem_path, O_RDONLY);
    if (fd < 0) {
        LOG("[-] Cannot open %s: %s", mem_path, strerror(errno));
        return -1;
    }
    
    if (lseek(fd, addr, SEEK_SET) < 0) {
        LOG("[-] Cannot seek to 0x%lx: %s", addr, strerror(errno));
        close(fd);
        return -1;
    }
    
    ssize_t n = read(fd, buf, len);
    close(fd);
    
    if (n < 0) {
        LOG("[-] Cannot read at 0x%lx: %s", addr, strerror(errno));
        return -1;
    }
    
    return (int)n;
}

// Scan for IL2CPP metadata magic (0xFAB11BAF in little-endian)
static long find_metadata(MemRegion *regions, int count) {
    LOG("[*] Scanning for IL2CPP metadata magic 0x%X...", METADATA_MAGIC);
    
    // Search in readable regions that are likely metadata (large anonymous mappings)
    for (int i = 0; i < count; i++) {
        MemRegion *r = &regions[i];
        
        // Skip regions that are too small or not readable
        unsigned long size = r->end - r->start;
        if (size < 1024 || r->perms[0] != 'r') continue;
        
        // Skip regions from shared libraries (we want anonymous or our lib)
        if (r->path[0] != '\0' && !strstr(r->path, g_lib_name) && !strstr(r->path, "[anon")) continue;
        
        // Skip very large regions (likely Java heap)
        if (size > 0x10000000) continue;
        
        // Read first 16KB of region and check for magic
        size_t check_size = size < 16384 ? size : 16384;
        uint8_t *buf = malloc(check_size);
        if (!buf) continue;
        
        int n = read_mem(r->start, buf, check_size);
        if (n >= 4) {
            for (int j = 0; j <= n - 4; j++) {
                uint32_t magic = *(uint32_t *)(buf + j);
                if (magic == METADATA_MAGIC) {
                    LOG("[+] Metadata found at 0x%lx (region: 0x%lx-0x%lx)",
                        r->start + j, r->start, r->end);
                    free(buf);
                    return (long)(r->start + j);
                }
            }
        }
        free(buf);
    }
    
    return -1;
}

// Extract printable strings from a memory region
static int extract_strings_from_region(unsigned long addr, size_t size, 
                                        FILE *out, int min_len) {
    uint8_t *buf = malloc(size);
    if (!buf) return 0;
    
    int n = read_mem(addr, buf, size);
    if (n <= 0) {
        free(buf);
        return 0;
    }
    
    int count = 0;
    char str[4096];
    int str_len = 0;
    
    for (int i = 0; i < n; i++) {
        if (buf[i] >= 0x20 && buf[i] <= 0x7E) {
            if (str_len < (int)sizeof(str) - 1) {
                str[str_len++] = buf[i];
            }
        } else {
            if (str_len >= min_len) {
                str[str_len] = '\0';
                fprintf(out, "0x%08lx: %s\n", addr + i - str_len, str);
                count++;
            }
            str_len = 0;
        }
    }
    
    // Don't forget the last string
    if (str_len >= min_len) {
        str[str_len] = '\0';
        fprintf(out, "0x%08lx: %s\n", addr + n - str_len, str);
        count++;
    }
    
    free(buf);
    return count;
}

// Extract all strings from the library
static int extract_all_strings(MemRegion *regions, int count, const char *output_file) {
    LOG("[*] Extracting printable strings from %s...", g_lib_name);
    
    FILE *out = fopen(output_file, "w");
    if (!out) {
        LOG("[-] Cannot create %s: %s", output_file, strerror(errno));
        return -1;
    }
    
    fprintf(out, "# Strings extracted from %s\n", g_lib_name);
    fprintf(out, "# PID: %d\n", g_pid);
    fprintf(out, "# Format: offset: string\n");
    fprintf(out, "#\n");
    
    int total = 0;
    for (int i = 0; i < count; i++) {
        MemRegion *r = &regions[i];
        if (!strstr(r->path, g_lib_name)) continue;
        if (r->perms[0] != 'r') continue;
        
        size_t size = r->end - r->start;
        if (size > MAX_DUMP_SIZE) size = MAX_DUMP_SIZE;
        
        total += extract_strings_from_region(r->start, size, out, 4);
    }
    
    fclose(out);
    LOG("[+] Extracted %d strings to %s", total, output_file);
    return total;
}

// Parse IL2CPP metadata and generate dump.cs
static int parse_metadata_and_dump(unsigned long metadata_addr, const char *output_file) {
    LOG("[*] Parsing IL2CPP metadata at 0x%lx...", metadata_addr);
    
    // Read header
    Il2CppGlobalMetadataHeader header;
    if (read_mem(metadata_addr, &header, sizeof(header)) < (int)sizeof(header)) {
        LOG("[-] Cannot read metadata header");
        return -1;
    }
    
    LOG("[+] Metadata version: %u", header.version);
    LOG("[+] TypeDefinitions: %u @ offset 0x%X", header.typeDefinitionsCount, header.typeDefinitionsOffset);
    LOG("[+] Methods: %u @ offset 0x%X", header.methodsCount, header.methodsOffset);
    LOG("[+] Fields: %u @ offset 0x%X", header.fieldsCount, header.fieldsOffset);
    LOG("[+] Images: %u @ offset 0x%X", header.imagesCount, header.imagesOffset);
    LOG("[+] Assemblies: %u @ offset 0x%X", header.assembliesCount, header.assembliesOffset);
    
    if (header.typeDefinitionsCount == 0) {
        LOG("[-] No type definitions found - metadata may be encrypted");
        return -1;
    }
    
    // Read all needed data blocks
    size_t type_def_size = header.typeDefinitionsCount * sizeof(Il2CppTypeDefinition);
    size_t method_def_size = header.methodsCount * sizeof(Il2CppMethodDefinition);
    size_t field_def_size = header.fieldsCount * sizeof(Il2CppFieldDefinition);
    size_t string_size = header.stringCount;
    
    uint8_t *type_defs = malloc(type_def_size);
    uint8_t *method_defs = malloc(method_def_size);
    uint8_t *field_defs = malloc(field_def_size);
    char *strings = malloc(string_size);
    
    if (!type_defs || !method_defs || !field_defs || !strings) {
        LOG("[-] Memory allocation failed");
        free(type_defs); free(method_defs); free(field_defs); free(strings);
        return -1;
    }
    
    read_mem(metadata_addr + header.typeDefinitionsOffset, type_defs, type_def_size);
    read_mem(metadata_addr + header.methodsOffset, method_defs, method_def_size);
    read_mem(metadata_addr + header.fieldsOffset, field_defs, field_def_size);
    read_mem(metadata_addr + header.stringOffset, strings, string_size);
    
    // Helper to get string from metadata string table
    #define GET_STR(idx) ((idx) < string_size ? &strings[(idx)] : "<invalid>")
    
    // Open output file
    FILE *out = fopen(output_file, "w");
    if (!out) {
        LOG("[-] Cannot create %s: %s", output_file, strerror(errno));
        free(type_defs); free(method_defs); free(field_defs); free(strings);
        return -1;
    }
    
    fprintf(out, "// IL2CPP Dump - Generated by OprekTool v0.16.0\n");
    fprintf(out, "// PID: %d | Library: %s | Metadata: 0x%lx\n", g_pid, g_lib_name, metadata_addr);
    fprintf(out, "// Metadata version: %u\n", header.version);
    fprintf(out, "// Types: %u | Methods: %u | Fields: %u\n\n",
            header.typeDefinitionsCount, header.methodsCount, header.fieldsCount);
    
    int dumped_types = 0;
    int dumped_methods = 0;
    
    // Parse each TypeDefinition
    for (uint32_t i = 0; i < header.typeDefinitionsCount; i++) {
        Il2CppTypeDefinition *td = (Il2CppTypeDefinition *)(type_defs + i * sizeof(Il2CppTypeDefinition));
        
        const char *type_name = GET_STR(td->nameIndex);
        const char *ns_name = GET_STR(td->namespaceIndex);
        
        // Filter out compiler-generated types
        if (strstr(type_name, "<") || strstr(type_name, "c__Iterator") ||
            strstr(type_name, "c__DisplayClass")) continue;
        
        fprintf(out, "// TypeDef index: %u (0x%X)\n", i, i);
        if (ns_name[0] != '\0') {
            fprintf(out, "namespace %s {\n", ns_name);
        }
        fprintf(out, "public class %s {\n", type_name);
        
        // Dump methods
        for (uint32_t m = td->methodStart; m < td->methodStart + td->method_count; m++) {
            if (m >= header.methodsCount) break;
            
            Il2CppMethodDefinition *md = (Il2CppMethodDefinition *)(method_defs + m * sizeof(Il2CppMethodDefinition));
            const char *method_name = GET_STR(md->nameIndex);
            
            fprintf(out, "    // Method index: %u\n", m);
            fprintf(out, "    public %s(%s) { }\n", 
                    method_name,
                    md->parameterCount > 0 ? "/* params */" : "");
            dumped_methods++;
        }
        
        // Dump fields
        for (uint32_t f = td->fieldStart; f < td->fieldStart + td->field_count; f++) {
            if (f >= header.fieldsCount) break;
            
            Il2CppFieldDefinition *fd = (Il2CppFieldDefinition *)(field_defs + f * sizeof(Il2CppFieldDefinition));
            const char *field_name = GET_STR(fd->nameIndex);
            
            fprintf(out, "    // Field index: %u\n", f);
            fprintf(out, "    public object %s;\n", field_name);
        }
        
        fprintf(out, "}\n");
        if (ns_name[0] != '\0') {
            fprintf(out, "} // namespace %s\n", ns_name);
        }
        fprintf(out, "\n");
        dumped_types++;
        
        if (dumped_types % 100 == 0) {
            LOG("[*] Progress: %u/%u types dumped...", dumped_types, header.typeDefinitionsCount);
        }
    }
    
    fclose(out);
    free(type_defs); free(method_defs); free(field_defs); free(strings);
    
    LOG("[+] Dump complete: %d types, %d methods -> %s", dumped_types, dumped_methods, output_file);
    return dumped_types;
}

// Main entry point
int main(int argc, char *argv[]) {
    if (argc < 4) {
        fprintf(stderr, "Usage: %s <pid> <lib_name> <output_dir>\n", argv[0]);
        fprintf(stderr, "Example: %s 12345 libil2cpp.so /sdcard/Download/OprekTool/dump\n", argv[0]);
        return 1;
    }
    
    g_pid = atoi(argv[1]);
    strncpy(g_lib_name, argv[2], sizeof(g_lib_name) - 1);
    strncpy(g_output_dir, argv[3], sizeof(g_output_dir) - 1);
    
    if (g_pid <= 0) {
        fprintf(stderr, "[-] Invalid PID: %s\n", argv[1]);
        return 1;
    }
    
    // Create output directory
    mkdir(g_output_dir, 0755);
    
    // Open log file
    char log_path[512];
    snprintf(log_path, sizeof(log_path), "%s/dumper.log", g_output_dir);
    g_log = fopen(log_path, "w");
    
    LOG("========================================");
    LOG("IL2CPP Dumper - OprekTool v0.16.0");
    LOG("PID: %d | Library: %s", g_pid, g_lib_name);
    LOG("Output: %s", g_output_dir);
    LOG("========================================");
    
    // Step 1: Read memory maps
    LOG("[*] Reading /proc/%d/maps...", g_pid);
    MemRegion *regions = malloc(sizeof(MemRegion) * MAX_REGIONS);
    if (!regions) {
        LOG("[-] Memory allocation failed");
        return 1;
    }
    
    int region_count = read_maps(regions, MAX_REGIONS);
    if (region_count <= 0) {
        LOG("[-] Cannot read memory maps");
        free(regions);
        return 1;
    }
    
    LOG("[+] Found %d memory regions", region_count);
    
    // Step 2: Find library base
    unsigned long lib_end = 0;
    unsigned long lib_base = find_lib_base(regions, region_count, &lib_end);
    
    if (lib_base == 0) {
        LOG("[-] Library %s NOT found in process memory!", g_lib_name);
        LOG("[*] Available .so files:");
        for (int i = 0; i < region_count; i++) {
            if (strstr(regions[i].path, ".so") && regions[i].path[0] != '\0') {
                LOG("    %s", regions[i].path);
            }
        }
        free(regions);
        return 1;
    }
    
    LOG("[+] Library base: 0x%lx", lib_base);
    LOG("[+] Library end:  0x%lx (%lu KB)", lib_end, (lib_end - lib_base) / 1024);
    
    // Step 3: Find metadata
    long metadata_addr = find_metadata(regions, region_count);
    
    // Step 4: Generate dump.cs
    char dump_path[512];
    snprintf(dump_path, sizeof(dump_path), "%s/dump_%s.cs", g_output_dir, g_lib_name);
    
    if (metadata_addr > 0) {
        LOG("[+] Valid metadata found! Parsing TypeDef/MethodDef/FieldDef...");
        int types = parse_metadata_and_dump((unsigned long)metadata_addr, dump_path);
        if (types > 0) {
            LOG("[+] dump.cs generated: %s", dump_path);
        } else {
            LOG("[-] Metadata parsing failed - generating raw dump");
            // Fallback: extract strings
            extract_all_strings(regions, region_count, dump_path);
        }
    } else {
        LOG("[-] Metadata NOT found (likely encrypted at runtime)");
        LOG("[*] Falling back to string extraction...");
        extract_all_strings(regions, region_count, dump_path);
    }
    
    // Step 5: Also extract strings separately
    char strings_path[512];
    snprintf(strings_path, sizeof(strings_path), "%s/strings_%s.txt", g_output_dir, g_lib_name);
    extract_all_strings(regions, region_count, strings_path);
    
    // Summary
    LOG("");
    LOG("========================================");
    LOG("DUMP COMPLETE");
    LOG("========================================");
    LOG("Files generated:");
    LOG("  %s", dump_path);
    LOG("  %s", strings_path);
    LOG("  %s/dumper.log", g_output_dir);
    LOG("");
    LOG("If dump.cs is empty/strings-only, the metadata is encrypted.");
    LOG("Use Il2CppDumper on PC with the .bin file for offline parsing.");
    LOG("========================================");
    
    if (g_log) fclose(g_log);
    free(regions);
    
    return 0;
}
