package com.oprek.tool.ui.screens

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.navigation.NavController
import com.oprek.tool.ui.theme.*
import kotlin.random.Random
import androidx.compose.material.icons.filled.ContentCopy
import androidx.compose.ui.graphics.Color

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun KeygenScreen(navController: NavController) {
    val context = LocalContext.current
    var length by remember { mutableStateOf("32") }
    var charset by remember { mutableStateOf("alnum") }
    var generated by remember { mutableStateOf("") }
    var count by remember { mutableStateOf("1") }

    Scaffold(
        topBar = {
            TopAppBar(title = { Text("🔑 Key Generator", fontWeight = FontWeight.Bold) },
                navigationIcon = { IconButton(onClick = { navController.popBackStack() }) { Icon(Icons.AutoMirrored.Filled.ArrowBack, "Back") } },
                colors = TopAppBarDefaults.topAppBarColors(containerColor = DarkBg))
        },
        containerColor = DarkBg
    ) { padding ->
        Column(Modifier.padding(padding).fillMaxSize().verticalScroll(rememberScrollState()).padding(12.dp)) {
            Card(Modifier.fillMaxWidth(), colors = CardDefaults.cardColors(containerColor = DarkCard), shape = RoundedCornerShape(12.dp)) {
                Column(Modifier.padding(12.dp)) {
                    Text("Config", fontWeight = FontWeight.Bold, fontSize = 14.sp, color = AccentOrange)
                    Spacer(Modifier.height(8.dp))
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        OutlinedTextField(value = length, onValueChange = { length = it }, label = { Text("Length") },
                            modifier = Modifier.width(80.dp), singleLine = true, colors = OutlinedTextFieldDefaults.colors(focusedBorderColor = AccentOrange))
                        Spacer(Modifier.width(12.dp))
                        OutlinedTextField(value = count, onValueChange = { count = it }, label = { Text("Count") },
                            modifier = Modifier.width(80.dp), singleLine = true, colors = OutlinedTextFieldDefaults.colors(focusedBorderColor = AccentOrange))
                    }
                    Spacer(Modifier.height(8.dp))

                    Text("Charset:", fontSize = 12.sp, color = TextSecondary)
                    Row(horizontalArrangement = Arrangement.spacedBy(6.dp)) {
                        listOf("alnum" to "AlphaNum", "hex" to "Hex", "num" to "Numeric", "alpha" to "Alpha", "all" to "All").forEach { (key, label) ->
                            FilterChip(selected = charset == key, onClick = { charset = key }, label = { Text(label, fontSize = 11.sp) },
                                colors = FilterChipDefaults.filterChipColors(selectedContainerColor = AccentOrange.copy(alpha = 0.3f)))
                        }
                    }
                }
            }
            Spacer(Modifier.height(12.dp))
            Button(onClick = {
                val chars = when (charset) {
                    "hex" -> "0123456789ABCDEF"
                    "num" -> "0123456789"
                    "alpha" -> "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
                    "all" -> "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*"
                    else -> "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
                }
                val len = length.toIntOrNull() ?: 32
                val n = (count.toIntOrNull() ?: 1).coerceIn(1, 100)
                generated = (1..n).joinToString("\n") {
                    (1..len).map { chars[Random.nextInt(chars.length)] }.joinToString("")
                }
            }, modifier = Modifier.fillMaxWidth(), colors = ButtonDefaults.buttonColors(containerColor = AccentOrange), shape = RoundedCornerShape(12.dp)) {
                Text("Generate", fontWeight = FontWeight.Bold)
            }
            if (generated.isNotEmpty()) {
                Spacer(Modifier.height(12.dp))
                Card(Modifier.fillMaxWidth(), colors = CardDefaults.cardColors(containerColor = DarkCard), shape = RoundedCornerShape(12.dp)) {
                    Column(Modifier.padding(12.dp)) {
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Text("Output", fontWeight = FontWeight.Bold, fontSize = 14.sp, color = AccentGreen, modifier = Modifier.weight(1f))
                            IconButton(onClick = {
                                val cb = context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
                                cb.setPrimaryClip(ClipData.newPlainText("key", generated))
                            }, modifier = Modifier.size(28.dp)) { Icon(Icons.Default.ContentCopy, "Copy", Modifier.size(16.dp), tint = AccentGreen) }
                        }
                        Spacer(Modifier.height(4.dp))
                        Text(generated, fontSize = 12.sp, fontFamily = FontFamily.Monospace, color = AccentGreen,
                            modifier = Modifier.fillMaxWidth().verticalScroll(rememberScrollState()))
                    }
                }
            }
            // Output to /sdcard/oprek-tool/output/
            Spacer(Modifier.height(12.dp))
            OutputButton(
                content = { "Keys generated" },
                filename = "keys.txt",
                subfolder = "keys"
            )

        }
    }
}
